<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Promise---Promise.resolve&Promise.reject</title>
</head>

<body>
    <script type="text/javascript">
    function show(arr) {
        console.log("");
        arr.forEach(function(key, i) {
            console.log(i + "", key);
        });
        console.log("");
    }

    /**
     * Promise.resolve()
     */

    // Promise Pending（进行中）、Fulfilled（已成功）和Rejected（已失败）
    // 当Promise状态为fulfilled时，调用 then 的 onfulfilled 方法，当Promise状态为rejected时，调用 then 的 onrejected 方法

    {
        // 直接返回一个Fulfilled状态的Promise
        Promise.resolve('foo');
        // 等价于
        new Promise((resolve, reject) => resolve('foo'));
    }




    /*Promise.resolve方法的参数分成四种情况。*/


    /*（1）参数是一个Promise实例*/
    // 如果参数是Promise实例，那么Promise.resolve将不做任何修改、原封不动地返回这个实例。
    {
        // 同理在构造函数中调用resolve()传入的参数也是一样
        let p1 = new Promise(function(resolve, reject) {
            setTimeout(() => reject(new Error('fail')), 3000)
        });
        let p2 = new Promise(function(resolve, reject) {
            setTimeout(() => resolve(p1), 1000)
        });
        p2
            .then(result => {
                console.log(result);
            })
            .catch(error => {
                console.log(error);
            });
        // Error: fail

        // p2 结果相当于返回一个 Promise.resolve(p1) => 等于直接返回p1 => p1还处于pending状态 => 返回 Promise.reject(new Error('fail'))

        // Promise对象 都是会返回一个状态以及状态对应的值(参数) , 如果那个状态对应的值(参数)是一个 新Promise对象 的时候 , Promise对象就直接返回 那个新的Promise对象
    }

    /*（2）参数是一个thenable对象*/
    {
        let thenable = {
            then: function(resolve, reject) {
                setTimeout(function() {
                    if (Math.random() > 0.5) {
                        resolve(200);
                    } else {
                        reject(400);
                    }
                }, 500);
            }
        };
        let p1 = Promise.resolve(thenable);
        p1.then(function(value) {
            console.log(value);
        }).catch((error) => {
            console.log(error);
        });

        // 200
        // 或者
        // 400

    }

    /*（3）参数不是具有then方法的对象，或根本就不是对象*/
    {
        // 如果参数是一个原始值，或者是一个不具有then方法的对象，则Promise.resolve方法返回一个新的Promise对象，状态为Resolved。
        let p = Promise.resolve('Hello');
        p.then(function(s) {
            console.log("参数情况三", s)
        });
        // 参数情况三 Hello
        // 由于字符串Hello不属于异步操作（判断方法是它不是具有then方法的对象），返回Promise实例的状态从一生成就是Resolved，所以回调函数会立即执行。Promise.resolve方法的参数，会同时传给回调函数。
    }

    /*（4）不带有任何参数*/
    {
        // Promise.resolve方法允许调用时不带参数，直接返回一个Resolved状态的Promise对象。


        // 需要注意的是，立即resolve的Promise对象，是在本轮“事件循环”（event loop）的结束时，而不是在下一轮“事件循环”的开始时。
        setTimeout(function() {
            console.log('three');
        }, 0);

        Promise.resolve().then(function() {
            console.log('two');
        });

        console.log('one');

        // one
        // two
        // three

        // setTimeout(fn, 0)在下一轮“事件循环”开始时执行，Promise.resolve()在本轮“事件循环”结束时执行，console.log(’one‘)则是立即执行，因此最先输出。
    }


    /**
     * Promise.reject()
     *
     * Promise.reject(reason)方法也会返回一个新的 Promise 实例，该实例的状态为rejected。
     *
     * Promise.reject()方法的参数，会原封不动地作为reject的理由，变成后续方法的参数。这一点与Promise.resolve方法不一致。
     */
    {
        const thenable = {
            then(resolve, reject) {
                reject('出错了');
            }
        };

        Promise.reject(thenable)
            .catch(error => {
                console.log(error)
            });
        //{then: ƒ}

        // 上面代码中，Promise.reject方法的参数是一个thenable对象，执行以后，后面catch方法的参数不是reject抛出的“出错了”这个字符串，而是thenable对象。
    }

    // end
    </script>
</body>

</html>
